---
title: "Lista avaliativa 2a – Probabilidade e Estatística – 2023.2"
author: "Juan Melo"
date: "2023-10-29"
output: html_document
---

```{r preparando, include=FALSE}
library(tidyverse)
if (!requireNamespace("RcppAlgos", quietly = TRUE)) {
  install.packages("RcppAlgos")
}
if (!requireNamespace("gtools", quietly = TRUE)) {
  install.packages("RcppAlgos")
  install.packages("gtools")
}
library(RcppAlgos)
library(gtools)
```

## Exercicio 1

```{r denominador}
varpop <- function(x) {
  n <- length(x)  # Tamanho da amostra
  variancia <- var(x)  
  N <- n + 1  
  corrected_variancia <- variancia * (n / N)  # Correcaoo para fazer a variância populacional
  return(corrected_variancia)
}


populacao <- c(1, 4, 10, 15)

# Gerando todos os arranjos possíveis de 3 elementos da população com reposição
amostras <- permutations(4, 3, populacao, repeats.allowed = TRUE)


variancia_populacional <- varpop(populacao)

# Usando a fórmula com N no denominador (varpop)
variancias_varpop <- apply(amostras, 1, varpop)

# Contagem das variâncias com fórmula de varpop menores,iguais ou maiores que a variância populacional
menor_varpop <- sum(variancias_varpop <= variancia_populacional)
maior_varpop <- sum(variancias_varpop > variancia_populacional)

# Cálculo da média das variâncias com a fórmula de varpop
media_varpop <- mean(variancias_varpop)

variancias_amostral <- apply(amostras, 1, var)  # Variância amostral (n-1)

menor_amostral <- sum(variancias_amostral <= variancia_populacional)
maior_amostral <- sum(variancias_amostral > variancia_populacional)

# Cálculo da média das variâncias amostrais com n-1 no denominador
media_amostral <- mean(variancias_amostral)

# Resultados
media_varpop
media_amostral
#Como esperado, o resultado da media amostral foi maior devido à maior precisao da formula com N-1.



```



```{r prob, echo=FALSE}

prob_canhotas <- choose(100, 0) * 0.88^100
prob_canhotas


prob_75destras <- sum(dbinom(0:75, size = 100, prob = 0.88))
prob_75destras

prob_maioriadestras <- sum(dbinom(51:100, size = 100, prob = 0.88))
prob_maioriadestras
```

