# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\x12\x06pubsub\"2\n\x0ePublishRequest\x12\x0f\n\x07torcida\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x10SubscribeRequest\x12\x0f\n\x07torcida\x18\x01 \x01(\t\"+\n\x07Message\x12\x0f\n\x07torcida\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2}\n\rPubSubService\x12\x38\n\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\x0f.pubsub.Message0\x01\x12\x32\n\x07Publish\x12\x16.pubsub.PublishRequest\x1a\x0f.pubsub.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=24
  _globals['_PUBLISHREQUEST']._serialized_end=74
  _globals['_SUBSCRIBEREQUEST']._serialized_start=76
  _globals['_SUBSCRIBEREQUEST']._serialized_end=111
  _globals['_MESSAGE']._serialized_start=113
  _globals['_MESSAGE']._serialized_end=156
  _globals['_PUBSUBSERVICE']._serialized_start=158
  _globals['_PUBSUBSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
